version: '3'

services:
  main:
    build: .
    volumes:
      - ./public:/work/public
      - ./src:/work/src
      - ./tests:/work/tests
      - ./yarn.lock:/work/yarn.lock
    ports:
      - 8080:8080
    tty: true
